### ISSUE TITLE
Errors reported by plugin when an empty VS Code window is opened.

### ISSUE THREAD

**Issue by adrianffletcher** [accordproject/cicero-vscode-extension#1] opened 2019-06-28 11:47 UTC
When a new empty window is created in VS Code the following error message is displayed: "The Cicero server crashed 5 times in the last 3 minutes. The server will not be restarted."

<img width="536" alt="Screen Shot 2019-06-28 at 12 19 22" src="https://user-images.githubusercontent.com/29235349/60340159-bd3aa680-99a2-11e9-8eee-3b987ad3f222.png">

[Kapture 2019-06-28 at 12.16.54.mp4.zip](https://github.com/accordproject/cicero-vscode-extension/files/3339030/Kapture.2019-06-28.at.12.16.54.mp4.zip)

**Comment by dselman** [comment] 2019-07-04 14:13
@jeromesimeon this seems to be caused by a failure to create the Ergo logger. Can we fall back to `console.log` or print a warning? It would appear that until you open a folder / workspace VSCode disables file system access?

```
Error: EACCES: permission denied, mkdir 'log'
    at Object.mkdirSync (fs.js:731:3)
    at setupLogger (/Users/dselman/dev/cicero-vscode-extension/client/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:113:16)
    at Object.<anonymous> (/Users/dselman/dev/cicero-vscode-extension/client/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:125:1)
    at Object.<anonymous> (/Users/dselman/dev/cicero-vscode-extension/client/server/node_modules/@accordproject/ergo-compiler/lib/logger.js:131:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
[Error - 3:12:02 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by dselman** [comment] 2019-07-04 14:17
It could be that the current working directory is set to `/` perhaps, causing the OS to block creation of '/log`?

https://github.com/accordproject/ergo/blob/master/packages/ergo-compiler/lib/logger.js#L124

**Comment by dselman** [comment] 2020-07-09 20:07
Closing as I cannot reproduce.

**Closed by dselman** 2020-07-09 20:07 UTC
Labels: Type: Bug 🐛
