### ISSUE TITLE
Highlighting acronyms

### ISSUE THREAD

**Issue by peterhunn** [accordproject/cicero-vscode-extension#13] opened 2019-09-16 18:48 UTC
**Describe the bug**
Syntax highlighting issues when writing acronyms in VS Code

**To Reproduce**
1. Go to VS Code
2. Build a Concerto model with acronyms as enumerated types
3. See lack of highlighting

**Expected behavior**
Acronyms should be highlighted in the same way as any other enumerated type

**Screenshots**
<img width="268" alt="Screenshot 2019-09-16 13 41 02" src="https://user-images.githubusercontent.com/9304034/64984306-289c6200-d888-11e9-9c08-babd96affe14.png">

**Desktop (please complete the following information):**
VS Code 3
MacOS

**Comment by peterhunn** [comment] 2019-10-10 19:19
Not to my knowledge @rajatrawataku1 - it's yours!

**Comment by irmerk** [comment] 2019-10-17 14:15
Moving this back to open after 7 days.

**Comment by whitehawk0011** [comment] 2019-10-22 08:26
can I take this one ?

**Comment by irmerk** [comment] 2019-10-28 19:40
@whitehawk0011 any progress on this?

**Comment by adrijshikhar** [comment] 2020-02-21 14:26
@irmerk can i work on this issue?
PS: i have already setup the repo

**Comment by adrijshikhar** [comment] 2020-02-22 11:42
is there any sample repo to test the extension?

**Comment by adrijshikhar** [comment] 2020-02-23 05:29
@peterhunn can you please provide the steps to reproduce the bug and give the exact data model to test on? Thanks

**Comment by peterhunn** [comment] 2020-03-07 23:47
> @peterhunn can you please provide the steps to reproduce the bug and give the exact data model to test on? Thanks

@adrijshikhar 

1. Go to VS Code
2. Build a new Concerto model with any enumerated types with a hyphen e.g. `CC-BY`
3. See lack of highlighting

**Comment by adrijshikhar** [comment] 2020-03-19 16:25
I tried to build a new Concerto model with enumerated types with a hyphen, and I noticed one more thing. If the enumerated type does not have a small character, the syntax highlighting does not take place. Is this supposed to happen, or its a bug? Correct me if I am wrong.

![Screenshot_20200319_215504](https://user-images.githubusercontent.com/41939219/77089876-62634680-6a2c-11ea-88b5-b717340b96ca.png)

**Comment by jeromesimeon** [comment] 2020-03-20 17:02
> I tried to build a new Concerto model with enumerated types with a hyphen, and I noticed one more thing. If the enumerated type does not have a small character, the syntax highlighting does not take place. Is this supposed to happen, or its a bug? Correct me if I am wrong.
> @jeromesimeon
> ![Screenshot_20200319_215504](https://user-images.githubusercontent.com/41939219/77089876-62634680-6a2c-11ea-88b5-b717340b96ca.png)

I believe this is not a valid CTO File (I don't think the parser allows `-` in enumerated names. So no I don't believe the lack of highlighting is a bug.

However, there should be a CTO parsing error: we should open an issue about that if it isn't properly reported by the VSCode extension.

**Comment by jeromesimeon** [comment] 2020-03-20 17:04
Also: lifting this back to the original issue, I don't think this has anything to do with acronyms, just we don't allow `-` in enums.

**Comment by adrijshikhar** [comment] 2020-03-20 17:31
The steps to reproduce says, `Build a new Concerto model with any enumerated types with a hyphen e.g. CC-BY`. Is this different from what I have created? Please correct me if I am wrong.

**Comment by adrijshikhar** [comment] 2020-03-20 19:49
> However, there should be a CTO parsing error: we should open an issue about that if it isn't properly reported by the VSCode extension.
@jeromesimeon I was making changes to a sample Concerto model, then it gave the error. So I thought I should try with a new model. That's why I made a test one.
![Screenshot_20200321_011751](https://user-images.githubusercontent.com/41939219/77201161-096dde00-6b12-11ea-9e0f-05aa4f4ca288.png)

**Comment by jeromesimeon** [comment] 2020-03-21 14:48
> However, there should be a CTO parsing error: we should open an issue about that if it isn't properly reported by the VSCode extension.
> @jeromesimeon I was making changes to a sample Concerto model, then it gave the error. So I thought I should try with a new model. That's why I made a test one.
> ![Screenshot_20200321_011751](https://user-images.githubusercontent.com/41939219/77201161-096dde00-6b12-11ea-9e0f-05aa4f4ca288.png)

As I said, I don't think `CC-BY` is a valid name for enums. We do not need to provide syntax highlighting for those, but we should make sure the error is reported (it seems like it is?).

I would close this issue as "invalid".

@peterhunn Any thoughts about this?

**Comment by peterhunn** [comment] 2020-03-23 02:49
@jeromesimeon if that is the correct technical approach I am fine with that, but would we always want that in models? What would the appropriate delineation b between valid and invalid?

**Comment by jeromesimeon** [comment] 2020-03-23 13:20
> @jeromesimeon if that is the correct technical approach I am fine with that, but would we always want that in models? What would the appropriate delineation b between valid and invalid?

@peterhunn That's a really good question. There is a syntax for CTO models which decides what is valid or invalid. At the moment `-` is not a valid character in identifiers. So `CCBY` is ok but `CC-BY` is not.

This is quite a common since you would quickly get into ambiguities in the logic if you allowed `-`: would `CC-BY` be an identifier or mean "CC minus BY" ? Attempting to change that would be something we have to tackle in Concerto itself (and Ergo).

My observation in this issue is that this isn't about syntax highlighting. The syntax highlighter should highlight properly valid models (and clearly indicate errors in the model). I hope that makes sense.

**Comment by dselman** [comment] 2020-03-24 11:11
Closing this issue. I will open a new issue around having localizable display names for enums.

**Closed by dselman** 2020-03-24 11:11 UTC
Labels: Good First Issue (Taken), Type: Feature Request 🛍️
